name: Run Tests

on:
  push:
    branches:
      - main  # Altere para o nome da branch que você deseja monitorar
  pull_request:
    branches:
      - main  # Altere para o nome da branch que você deseja monitorar

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'  # Altere para a versão do Python que você está usando

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest  # Instala pytest e outras dependências, se necessário

    - name: Run tests
      run: |
        pytest  # Executa os testes
